<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SDL</RootNamespace>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);SYSLIB1054;CA1401</NoWarn>
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <Authors>ppy Pty Ltd</Authors>
    <Company>ppy Pty Ltd</Company>
    <Copyright>Copyright (c) 2024 ppy Pty Ltd</Copyright>
    <Product>ppy.SDL3-CS</Product>
    <PackageId>ppy.SDL3-CS</PackageId>
    <PackageReleaseNotes>Automated release.</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ppy/SDL3-CS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ppy/SDL3-CS</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JetBrains.Annotations\JetBrains.Annotations.csproj" />
  </ItemGroup>

</Project>
